### ISSUE TITLE
bcf2000: exclude groups of fader mapping

### ISSUE THREAD

**Issue by leohz13** [justlep/bitwig#12]
the 8 motorized faders are mapped to tracks 1-8, 9-17,..  When e.g. grouping tracks 1-8 , the group also gets assigned to a fader, track 8 is not longer part of the first 8 faders.
So is it possible to exclude groups from midi mapping so only my actual tracks get mapped?

thanks in advance and have a nice one!
Leo

![Screenshot 2021-06-23 222601](https://user-images.githubusercontent.com/44744929/123163456-062e7400-d472-11eb-9371-c62a1f56ee2f.png)

**Comment by justlep** [comment]
Currently I don't see anything in the Bitwig API docs useful to make TrackBanks filter for non-group tracks only. 

If such functionality gets added, I'll be happy to integrate it into my script.
