### ISSUE TITLE
X-Touch Compact Issues

### ISSUE THREAD

**Issue by grizeldi** [justlep/bitwig#16]
First of all, thank you for your work on the scripts, they are a great starting point for getting things to work. That said, I just got an X-Touch compact and am trying to get it to work with Bitwig. With the script from this repo it mostly works, but there are some rather annoying issues.

1. The knobs don't really work. When I turn them, the values they control change seemingly at random. My guess is that something with value ranges is wrong, I'll have to investigate further.
2. No matter how many times I try pressing `SHIFT + Type/MIX` keys, I can't seem to get the controller into the MIX mode as described in the documentation.
3. The lights in the buttons don't seem to be working at all, which makes keeping track in which mode you currently are rather difficult.

I'll keep this issue updated as I investigate further and attempt some fixes.

**Comment by justlep** [comment]
Sounds much like incorrect midi settings in your Compact.
Have you dumped my LayerA preset onto the device?
https://raw.githubusercontent.com/justlep/bitwig/master/doc/Behringer%20X-Touch%20Compact/LayerA.bin

If that doesn't help, I can make screenshots of all the X-Touch Editor pages later today, so you can double-check if there's a mismatch somewhere.

**Comment by grizeldi** [comment]
Not yet, as the documentatiom states the default layer A preset is
required, so I assumed what the X-Touch Compact comes with out of the box
should be fine. I'll find a windows PC, try flashing, retest and report
back.

**Comment by grizeldi** [comment]
With reflashing the provided layerA.bin to the device, problems 1 and 2 are now resolved, so most of the functionality is there now, thanks.

However, all of the buttons still only light up when pressed, otherwise the only button that is glowing is the layer A button.

**Comment by justlep** [comment]
Oh wow, looks like the default settings of the device have changed a bit.. I'll update that in the docs.

For the buttons..
can you verify in the X-Touch Editor that **GLOBAL CH** is set to "CH 13"?
Maybe that setting is not saved in the .bin file.

**Comment by grizeldi** [comment]
The GLOBAL CH was set to 2 by default. After I manually changed it to 13, the buttons now light up as intended. So with a slight tweak to the documentation, I believe this issue can be closed.

Thank you for your help.

**Comment by justlep** [comment]
Cool, happy it works for you now, and thanks again for reporting the issue!
