### ISSUE TITLE
Behringer X-Touch Compact replacement caps

### ISSUE THREAD

**Issue by staltz** [justlep/bitwig#17]
Hey, thanks so much for this project, it truly helps a lot and since the code is open allows for further customization.

You mentioned that the X-Touch encoders can be replaced. How exactly did you remove the original ones and put the new ones? I don't want to accidentally end up damaging my device.

Thanks in advance

**Comment by justlep** [comment]
Hey, thank you for your kind words.

The encoder caps sit on a 6mm D-type plastic axis. They are tight but not glued, you can pull them off by hand with some careful force. I have done it multiple times, none of the encoders got damaged (same for the X-Touch Mini).

My new encoder caps I [bought here ](https://www.reichelt.de/de/de/potentiometerknopf-fuer-achse-6-mm-schwarz-knopf-13-164b-p73963.html?GROUPID=3139&&r=1) are not D-Type, but sit tightly and work perfectly. Their hole was 3mm to deep for the axis though, so I had to insert a little 3mm metal ball from a key chain before popping them on.

Hope that helps :)

![caps-1](https://github.com/justlep/bitwig/assets/13500168/94c3b3a4-3bbb-40d4-8e9f-dcfa3788497b)
![caps-2](https://github.com/justlep/bitwig/assets/13500168/718c4c69-ffdd-4f8d-b190-0c02745266b9)

**Comment by staltz** [comment]
Extremely useful tips, thank you!

Yeah I think I'll end up buying these, because indeed the original encoder caps seem like they were *meant* to be slippery, which makes absolutely no sense.
